config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products do
    resources :carts
  end
  get 'home/users'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

  belongs_to :user
  has_many :cart_products
  has_many :products, through: :cart_products
  
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  
  has_many :cart_products
  has_many :carts, through: :cart_products

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { :greater_than_or_equal_to => 0 }
  validates :image_url, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :cart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  after_action :add_product_to_cart, only: [:create, :update]
  respond_to :html, :js

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(user: current_user)

    respond_to do |format|
      @cart.save
      format.html { redirect_to product_path(params[:product_id]), flash[:success] = "Product added to cart" }
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json

# LES NOTICE / FLASH NE MARCHENT PAS. A ADAPTER A AJAX

  def update
    flash[:success] = "Product added to cart"
    redirect_to product_path(params[:product_id])
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_product_to_cart
    @product = Product.find(params[:product_id])
    CartProduct.create!(cart: @cart, product: @product)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find_by(user: current_user)
    end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.user %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @cart.user %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans:300' type='text/css' />
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all'%>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
  <!-- Omnisearch -->
  <div id="omnisearch" class="omnisearch">
    <div class="container">
      <!-- Search form -->
      <form class="omnisearch-form">
        <div class="form-group">
          <div class="input-group input-group-merge input-group-flush">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-search"></i></span>
            </div>
            <input type="text" class="form-control" placeholder="Type and hit enter ...">
          </div>
        </div>
      </form>
      <div class="omnisearch-suggestions">
        <h6 class="heading">Search Suggestions</h6>
        <div class="row">
          <div class="col-sm-6">
            <ul class="list-unstyled mb-0">
              <li>
                <a class="list-link" href="#">
                  <i class="fas fa-search"></i>
                  <span>macbook pro</span> in Laptops
                </a>
              </li>
              <li>
                <a class="list-link" href="#">
                  <i class="fas fa-search"></i>
                  <span>iphone 8</span> in Smartphones
                </a>
              </li>
              <li>
                <a class="list-link" href="#">
                  <i class="fas fa-search"></i>
                  <span>macbook pro</span> in Laptops
                </a>
              </li>
              <li>
                <a class="list-link" href="#">
                  <i class="fas fa-search"></i>
                  <span>beats pro solo 3</span> in Headphones
                </a>
              </li>
              <li>
                <a class="list-link" href="#">
                  <i class="fas fa-search"></i>
                  <span>smasung galaxy 10</span> in Phones
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="main-content">

    <!-- Header -->
    <section class="slice slice-xl bg-cover bg-size--cover" data-offset-top="#header-main" style="background-image: url(../../assets/img/backgrounds/img-16.jpg); background-position: center center;">
      <span class="mask bg-dark opacity-3"></span>
      <div class="container py-6">
        <div class="row justify-content-center">
          <div class="col-lg-6 text-center">
            <h2 class="h1 text-white">Home Accessories</h2>
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark px-0 justify-content-center">
              <li class="breadcrumb-item">
                <a href="#" class="">Home</a>
              </li>
              <li class="breadcrumb-item">
                <a href="#" class="text-normal">Shop</a>
              </li>
              <li class="breadcrumb-item">
                <a href="#" class="text-normal">Home Accessories</a>
              </li>
            </ol>
            <p class="lead text-white mt-4">There is only that moment and the incredible certainty that everything under the sun has been written by one hand only.</p>
            <a href="#" class="btn btn-white rounded-pill mt-4 shadow hover-shadow-lg hover-translate-y-n3">Start shopping</a>
          </div>
        </div>
      </div>
    </section>

    <!-- Products -->
    <section class="slice slice-lg delimiter-bottom" id="sct-products">
        <div class="container">
          <div class="row">
              <% @products.each do |product| %>
              <div class="col-md-4 mb-4">
                <div class="card card-product">
                  <div class="card-image">
                      <img alt="Image placeholder" src="<%= product.image_url %>" class="img-center img-fluid">
                  </div>
                  <div class="card-body text-center pt-0">
                    <h6><a href="#"><%= product.title %></a></h6>
                    <p class="text-sm">
                      <%= product.description %>
                    </p>
                    <span class="card-price"><%= product.price %> €</span>
                    <div class="product-colors mt-3">
                      <a href="#" style="background-color: #59ad46;" data-toggle="tooltip" data-original-title="Green"></a>
                      <a href="#" style="background-color: #04050a;" data-toggle="tooltip" data-original-title="Black"></a>
                      <a href="#" style="background-color: #62aedd;" data-toggle="tooltip" data-original-title="Blueish"></a>
                      <a href="#" style="background-color: #e84385;" data-toggle="tooltip" data-original-title="Pink"></a>
                    </div>
                    <%= link_to 'Voir le chaton', product, class: "btn btn-primary btn-icon" %>
                  </div>
                  <div class="actions card-product-actions" data-animation-in="slideInLeft" data-animation-out="slideOutLeft">
                    <button type="button" class="action-item" data-toggle="tooltip" data-original-title="Add to cart">
                      <i class="fas fa-shopping-bag"></i>
                    </button>
                    <button type="button" class="action-item" data-toggle="tooltip" data-original-title="Wishlist">
                      <i class="fas fa-heart"></i>
                    </button>
                  </div>
                </div>
                </div>
              <% end %>
          </div>
        </div>
    </section>
      
    <section class="slice slice-xl bg-cover bg-size--cover" style="background-image: url(../../assets/img/backgrounds/img-17.jpg); background-position: center center;">
      <span class="mask bg-dark opacity-2"></span>
      <div class="container py-6">
        <div class="row justify-content-center">
          <div class="col-lg-6 col-xl-6 text-center">
            <div class="mb-5">
              <h1 class="text-white">Always on time</h1>
              <p class="lead text-white mt-2">You get all Bootstrap components fully customized. Besides, you receive another numerous plugins out of the box and ready to use.</p>
            </div>
            <form>
              <div class="form-group mb-0">
                <div class="input-group input-group-lg input-group-merge rounded-pill bg-white">
                  <input type="email" class="form-control form-control-flush" name="email" placeholder="Enter your email address" aria-label="Enter your email address">
                  <div class="input-group-append">
                    <button class="btn btn-white text-dark" type="button">
                      <span class="far fa-paper-plane"></span>
                    </button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
    <section class="slice-sm bg-primary">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 mb-4 mb-lg-0">
            <div class="px-4 py-3 text-lg-center">
              <h6 class="text-sm text-white text-uppercase ls-1">Free shipping in 48/72H</h6>
              <p class="text-white opacity-7">
                Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod
              </p>
            </div>
          </div>
          <div class="col-lg-4 mb-4 mb-lg-0">
            <div class="px-4 py-3 text-lg-center">
              <h6 class="text-sm text-white text-uppercase ls-1">Free returns</h6>
              <p class="text-white opacity-7">
                Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod
              </p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="px-4 py-3 text-lg-center">
              <h6 class="text-sm text-white text-uppercase ls-1">Secure payment</h6>
              <ul class="list-inline mt-2">
                <li class="list-inline-item">
                  <img alt="Image placeholder" src="../../assets/img/icons/cards/visa.png" width="30">
                </li>
                <li class="list-inline-item">
                  <img alt="Image placeholder" src="../../assets/img/icons/cards/mastercard.png" width="30">
                </li>
                <li class="list-inline-item">
                  <img alt="Image placeholder" src="../../assets/img/icons/cards/maestro.png" width="30">
                </li>
                <li class="list-inline-item">
                  <img alt="Image placeholder" src="../../assets/img/icons/cards/paypal.png" width="30">
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>